[package]
name = "enum-from"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.36"
proc-macro2 = "1.0.86"

[dependencies.syn]
version = "2.0.72"
features = ["full"]
